export const ADD_DATA = 'ADD_DATA'
export const UPDATE_DATA = 'UPDATE_DATA'
export const DELETE_DATA = 'DELETE_DATA'
export const READ_ALL_DATA = 'READ_ALL_DATA'
export const READ_DATA = 'READ_DATA'
export const EMPTY_DATA = 'EMPTY_DATA'
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN'